id: IA45EB93A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-17T18:42:30+00:00'
last_modified: '2022-06-07T10:43:07.940426+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8284
  title: ཕར་ཕྱིན་གྱི་མཐའ་དཔྱོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    F2FC:
      image_group_id: I1KG15812
      title: Volume 1 of phar phyin gyi mtha' dpyod
      total_pages: 464
      order: 1
      base_file: F2FC.txt
    D4CA:
      image_group_id: I1KG15813
      title: Volume 2 of phar phyin gyi mtha' dpyod
      total_pages: 430
      order: 2
      base_file: D4CA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
